resources:
  'entity:log':
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
  is_logged_in_resource:
    GET:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
